name: Release

on:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Checkout SIFT3D
        uses: actions/checkout@v7
        with:
          repository: fatimp/sift3d
          path: sift3d
      - name: Checkout Faiss
        uses: actions/checkout@v7
        with:
          repository: facebookresearch/faiss
          path: faiss
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential cmake libblas-dev \
          liblapack-dev libopenblas-dev liblmdb-dev libopenblas-openmp-dev \
          liblapacke-dev libtiff-dev
      - name: Build SIFT3D
        run: |
          cd $GITHUB_WORKSPACE/sift3d
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DWITH_EXAMPLES=OFF ..
          make -j4 && sudo make install
      - name: Build Faiss
        run: |
          cd $GITHUB_WORKSPACE/faiss
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=ON \
          -DFAISS_ENABLE_C_API=ON -DBUILD_TESTING=OFF -DFAISS_ENABLE_GPU=OFF \
          -DFAISS_ENABLE_PYTHON=OFF ..
          make -j4 && sudo make install
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install qlot
        run: |
          ros install qlot
      - name: Set Path
        run: |
          echo "${HOME}/.roswell/bin" >> $GITHUB_PATH
      - name: Build soil-align
        run: |
          cd $GITHUB_WORKSPACE
          export LD_LIBRARY_PATH=/usr/local/lib
          qlot install
          qlot exec ros dynamic-space-size=100gb -e '(asdf:make :soil-align)'
      - name: Get version
        uses: nowsprinting/check-version-format-action@v5
        id: version
        with:
          prefix: 'v'
      - name: Prepare release
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p soil-align-amd64/usr/bin \
          soil-align-amd64/usr/lib/x86_64-linux-gnu \
          soil-align-amd64/DEBIAN
          cp src/soil-align soil-align-amd64/usr/bin
          cp /usr/local/lib/libfaiss*  soil-align-amd64/usr/lib/x86_64-linux-gnu
          cp /usr/local/lib/libsift3D* soil-align-amd64/usr/lib/x86_64-linux-gnu
          cat > soil-align-amd64/DEBIAN/control << EOF
          Package: soil-align
          Version: ${{ steps.version.outputs.full_without_prefix }}
          Architecture: amd64
          Maintainer: Vasily Postnicov <postnicov.vv@mipt.ru>
          Depends: libblas3, liblapack3, libopenblas0, libopenblas0-openmp, liblapacke, libtiff6
          Conflicts: libfaiss, libfaiss-dev
          Description: A tool for 3D image registration
          EOF
          cat soil-align-amd64/DEBIAN/control
          dpkg-deb --build soil-align-amd64 \
          soil-align-amd64-${{ steps.version.outputs.full_without_prefix }}.deb
      - name: Make a Release
        uses: softprops/action-gh-release@v3
        with:
          files: soil-align-amd64-${{ steps.version.outputs.full_without_prefix }}.deb
